### ISSUE TITLE
Add request tracing

### ISSUE THREAD

**Issue by dcseifert** [unbasical/kelon#160]
Kelon should be enabled with a tracing feature which makes it possible to have a full trace of all requests going through kelons (including round-trips to datastore).

[Open Tracing](https://github.com/opentracing/opentracing-go) might be a good start here.

**Comment by nelsonunbasicalgillo** [comment]
Implemented in #232 via [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-go)
