### ISSUE TITLE
Extend OPA with builtin functions via kelon config

### ISSUE THREAD

**Issue by dcseifert** [unbasical/kelon#254]
Due to the fact that the SQL-Statements that kelon produces might become very large and hard to troubleshoot over time it should be possible to register OPA builtin-functions that are translated direclty into SQL-Functions via the Datastore-Operand-Mappings. With this feature large SQL-Join-Queries can be moved inside the corresponding datastore and just called by kelon.

**Comment by containerpope** [comment]
@dcseifert @nelsonunbasicalgillo sounds good to me. We should move forward with a small RFC for that.

**Comment by nelsonunbasicalgillo** [comment]
Implemented in #261
